@echo off
AMIDEWINx64.exe /IVN %RANDOM%%RANDOM%%RANDOM%
AMIDEWINx64.exe /IV %RANDOM%%RANDOM%%RANDOM%
AMIDEWINx64.exe /ID %RANDOM%%RANDOM%%RANDOM%
AMIDEWINx64.exe /SM %RANDOM%%RANDOM%%RANDOM%
AMIDEWINx64.exe /SP %RANDOM%%RANDOM%%RANDOM%
AMIDEWINx64.exe /SV %RANDOM%%RANDOM%%RANDOM%
AMIDEWINx64.exe /SS %RANDOM%%RANDOM%%RANDOM%
AMIDEWINx64.exe /SU %RANDOM%%RANDOM%%RANDOM%
AMIDEWINx64.exe /SK %RANDOM%%RANDOM%%RANDOM%
AMIDEWINx64.exe /SF %RANDOM%%RANDOM%%RANDOM%
AMIDEWINx64.exe /BM %RANDOM%%RANDOM%%RANDOM%
AMIDEWINx64.exe /BP %RANDOM%%RANDOM%%RANDOM%
AMIDEWINx64.exe /BV %RANDOM%%RANDOM%%RANDOM%
AMIDEWINx64.exe /BS %RANDOM%%RANDOM%%RANDOM%
AMIDEWINx64.exe /BT %RANDOM%%RANDOM%%RANDOM%
AMIDEWINx64.exe /BLC %RANDOM%%RANDOM%%RANDOM%
AMIDEWINx64.exe /CM %RANDOM%%RANDOM%%RANDOM%
AMIDEWINx64.exe /CV %RANDOM%%RANDOM%%RANDOM%
AMIDEWINx64.exe /CS %RANDOM%%RANDOM%%RANDOM%
AMIDEWINx64.exe /CA x%RANDOM%%RANDOM%%RANDOM%
AMIDEWINx64.exe /CSK %RANDOM%%RANDOM%%RANDOM%
AMIDEWINx64.exe /PSN %RANDOM%%RANDOM%%RANDOM%
AMIDEWINx64.exe /PAT %RANDOM%%RANDOM%%RANDOM%
AMIDEWINx64.exe /PPN %RANDOM%%RANDOM%%RANDOM%
timeout 1 >nul
exit